src/AspNetCoreMvcHtmx/Models/ErrorViewModel.cs
namespace AspNetCoreMvcHtmx.Models;

public class ErrorViewModel
{
  public string? RequestId { get; set; }

  public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/AspNetCoreMvcHtmx/Models/Registration.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreMvcHtmx.Models;

public class Registration
{
  [Display(Name = "First name")]
  [Required]
  public string? FirstName { get; set; }
  [Required]
  [Display(Name = "Last name")]
  public string? LastName { get; set; }
  [Required]
  [Display(Name = "Company")]
  public string? CompanyName { get; set; }
  [Required]
  [Display(Name = "Password")]
  public string? Password { get; set; }
  [Required]
  [Display(Name = "Email")]
  [EmailAddress]
  public string? Email { get; set; }
}

public class PasswordValidation
{
  public int? PasswordScore { get; set; }
  [Required]
  public string? Password { get; set; }
}

src/AspNetCoreMvcHtmx/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreMvcHtmx.Models;

namespace AspNetCoreMvcHtmx.Controllers;

public class HomeController : Controller
{
  private readonly ILogger<HomeController> _logger;

  public HomeController(ILogger<HomeController> logger)
  {
    _logger = logger;
  }

  public IActionResult Index()
  {
    return View();
  }

  public IActionResult Privacy()
  {
    return View();
  }

  [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
  public IActionResult Error()
  {
    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
  }
}

src/AspNetCoreMvcHtmx/Controllers/RegistrationController.cs
using AspNetCoreMvcHtmx.Models;
using Easy_Password_Validator;
using Easy_Password_Validator.Models;
using Microsoft.AspNetCore.Mvc;
using static AspNetCoreMvcHtmx.Controllers.Constants;

namespace AspNetCoreMvcHtmx.Controllers;

public class RegistrationController : Controller
{
  public IActionResult Index()
  {
    return View();
  }

  [HttpPost]
  [Route("/api/registration")] //same route but different "Consumes"
  [Consumes(FormUrlEncoded)]
  public ActionResult PostForm([FromForm] Registration registration)
  {
    if (!ModelState.IsValid)
    {
      return PartialView("_RegistrationForm", registration);
    }


    return PartialView("_RegistrationSucceeded", registration);
  }

  [HttpPost]
  [Route("/api/registration")]
  [Consumes(ApplicationJson)]
  public ActionResult PostJson([FromBody] Registration registration)
  {
    if (!ModelState.IsValid)
    {
      var validation = new ValidationProblemDetails(ModelState)
      {
        Status = StatusCodes.Status422UnprocessableEntity
      };
      return UnprocessableEntity(validation);
    }


    return Created($"/user/{Guid.NewGuid()}", new { registration.FirstName });
  }

  [HttpPost]
  [Route("/api/passwordvalidation", Name = "passwordvalidation")]
  public IActionResult PasswordValidation([FromForm] PasswordValidation passwordValidation)
  {
    if (string.IsNullOrWhiteSpace(passwordValidation.Password))
    {
      return PartialView("_PasswordStrength", new PasswordValidation() { PasswordScore = null });
    }

    var validator = new PasswordValidatorService(new PasswordRequirements());
    validator.TestAndScore(passwordValidation.Password);
    return PartialView("_PasswordStrength", new PasswordValidation() { PasswordScore = validator.Score });
  }
}

src/AspNetCoreMvcHtmx/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}

<div class="text-center">
  <h1 class="text-4xl">Welcome</h1>
  <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/AspNetCoreMvcHtmx/Views/Shared/_Layout.cshtml
@using Htmx.TagHelpers
<!DOCTYPE html>
<html lang="en" class="h-full">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="htmx-config" includeAspNetAntiforgeryToken="true" />
  <title>@ViewData["Title"] - AspNetCoreMvcHtmx</title>
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
   <script src="~/lib/htmx.org/dist/htmx.min.js"></script>
</head>

<body class="h-full">
  <header class="bg-white drop-shadow-md">
    <nav class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8" aria-label="Top">
      <div class="flex items-center justify-between w-full py-6">
        <div class="flex items-center">
          <a href="#" class="text-base font-medium text-gray-600 hover:text-gray-400">
            AspNetCoreMvcHtmx
          </a>
          <div class="hidden ml-10 space-x-8 lg:block">
            <a asp-action="Index" asp-controller="Home" class="text-base font-medium text-gray-600 hover:text-gray-400"> Home </a>

            <a asp-action="Privacy" asp-controller="Home" class="text-base font-medium text-gray-600 hover:text-gray-400"> Privacy </a>
            <a asp-action="Index" asp-controller="Registration" class="text-base font-medium text-gray-600 hover:text-gray-400"> Registration </a>
          </div>
        </div>

      </div>
      <div class="flex flex-wrap justify-center py-4 space-x-6 lg:hidden">

        <a asp-page="/Index" class="text-base font-medium text-gray-600 hover:text-gray-400"> Home </a>

        <a asp-page="/Privacy" class="text-base font-medium text-gray-600 hover:text-gray-400"> Privacy </a>
        <a asp-page="/Registration" class="text-base font-medium text-gray-600 hover:text-gray-400"> Registration </a>
      </div>
    </nav>
  </header>

  <div class="p-4 m-4">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>


  <footer class="bg-white sticky top-[100vh] border-solid border-t border-t-gray-200">
    <div class="px-4 py-4 mx-auto max-w-7xl sm:px-6 md:flex md:items-center md:justify-between lg:px-8">

      <div class="mt-8 md:mt-0 md:order-1">
        <p class="text-base text-center text-gray-600">&copy; 2022 - AspNetCoreMvcHtmx - <a asp-action="Privacy"
            class="text-blue-500" asp-controller="Home">Privacy</a>
        </p>
      </div>
    </div>
  </footer>

@Html.HtmxAntiforgeryScript()
@await RenderSectionAsync("Scripts", required: false)
</body>

</html>